# 函数



`def` `FunctionName():`

​    `Block`

上为python函数格式，由`def` 关键字加上函数名 加 `:` 然后就是缩进与语句块(函数体)

- 函数在被调用时执行，而不是在被定义时



## 3.1 - def语句和参数

```python
def hello(name):
    print('hello' + name)

hello('Chikie')

#输出 hello Chikie
```

在函数定义的一块，函数括号内的变量为函数的参数(形参)，在调用函数时需要传递给函数参数

这里传递了字符串给 `hello()` `print()`函数将字符串相加并输出字符串



## 3.2 - 返回值和return语句

```python
def GetLength(str):
    return len(str)
length =  GetLength('Chikie')
print(length)

#输出6
```



`return`将函数内的值返回



**`randdom`模块**

```python
#需要先引入模块
import random

n = random.randint(0, 9)
#输出一个0-9范围内的随机数
```

`randint()`函数第一个参数为下界，第二个参数为上界，否则报错



## 3.3 - None值

`None`表示没有值， 与C或C++的 `NULL`类似

`print()`会返回 `None`类型的返回值

- 对于没有显示使用 `return`语句的函数，python回隐式加上 `return` 没有返回值，也就是 `None`



## 3.4 - 关键字参数和print()函数

`print()`有可选的参数

可以在要输出的内容后加上关键字 `end` 来指定在输出内容末尾加上什么，默认为换行符；或 使用关键字`sep`来指定在参数之间用什么来分隔它们



```python
print('Hello')
print('World')
#Hello World

print('Hello', end='') #在末尾输出空格
#HelloWorld

print('dog', 'mice', 'cat')
#dog mice cat

print('dog', 'mice', 'cat', sep=',') #使用逗号分隔参数
#dog,mice,cat
```



## 3.5 - 调用栈

当函数嵌套调用时，就如栈处理的顺序一样，分别运行各函数(有学过数据结构的应该很好理解，这里不讲解)



## 3.6 - 局部和全局作用域

python程序内部只有全局与局部两个作用域，在函数外部的变量处于全局作用域，反之为局部作用域

- 局部作用域的变量不能在全局作用域中使用
- 局部作用域不能使用其他局部作用域中的变量
- 局部作用域可以读取全局作用域中的变量
- 在局部作用域中的变量名可以与全局作用域中的相同，局部回覆盖全局



## 3.7 - global语句

如果需要在一个函数内修改全局变量，使用 `global`语前缀声明变量

```python
def Change():
    global name
    name = 'Van'
    
name = 'Chikie'
Change()
print(name)
#Van
```



以下为局部与全局变量示例

```python
def Func1():
    name = 'Van'
    print(name)
    
def Func2():
    global name
    print(name)

def Func3():
    print(name)
    
name = 'Chikie'
Func1()
Func2()
Func3()

'''
输出
Van
Chikie
Chikie
'''
```



**注意**

```python
def Func():
    print(name)
    name = 'Van Dark'
    
name = 'Chikie'
Func()

'''
错误
'name' referenced before assignment
在局部变量定义之前使用
'''
```



## 3.8 - 异常处理

```python
def Division(num):
    return 42 / num

print(Division(2)) #21
print(Division(3)) #14
print(Division(0)) #错误，程序终止
#出现 ZeroDivisionError错误
```



在程序中，错误经常发生，特别是逻辑不完善的程序，当程序出错时会终止运行

我们可以使用  `try`和`except`语句来处理运行中的错误

我们通常将可能出错的程序语句放在`try`语句块内，而 `excpet`负责捕捉与匹配错误



改进程序示例

```python
def Division(num):
    try:
        return 42 / num
    except ZeroDivisionError:
        print('You can not use Zero!')

print(Division(0))
#You can not use Zero!
```



